kind: pipeline
type: docker
name: hello-world

steps:
- name: backend
  pull: if-not-exists
  image: golang:1.13
  commands:
  - "go build -o ./myapp"
  
- name: docker  
  image: plugins/docker
  settings:
    # registry: docker.io
    repo: annisaseptiani/drone-test
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 
      - latest

trigger:
  branch:
  - master
